In [3]:
x=10
if x>5:
    print("x is greter than 5")
else:
    print("x is not greter than 5")


x is greter than 5


In [2]:
y=15
if y<10:
    print("y is less than 10")
elif y>=10 and y<20:
    print("y is between 10 and 19")
else:
    print("y is 20 or greter")

y is between 10 and 19


In [4]:
fruits=['banana','apple','orange']
if 'banana' in fruits:
    print("banana in the list")
else:
    print("banana not in the list")


banana in the list


In [ ]:
Nested if statement

In [12]:
num=int(input("Enter any number"))
if num>0:
    if num%2==0:
        print("+ve even number")
    else:
        print("+ve odd number")
elif num==0:
    print("zero")

+ve even number


In [13]:
a=7
b=10
result="a is greter" if a>b else " b is greter or equal"
print(result)

 b is greter or equal


In [15]:
value=" "
if value is None:
    print("The value is None")
elif value==" ":
    print("The value is empty string")
else:
    print(f("the value is : {value}"))

The value is empty string


In [ ]:
Checking for Membership in Multiple Lists

In [16]:
colors=['green','red','orange']
selected_color='green'
if selected_color in colors:
    print(f"{selected_color} is available in the list")
else:
    print(f"{selected_color} is not in the list")



green is available in the list


In [ ]:
Example 3: Using all and any with Lists

In [17]:
numbers=[1,2,3,4,5]
if all(num>0 for num in numbers):
    print("all  numbers are positive")
elif any(num%2==0 for num in numbers):
    print("at least one number is even")
else:
    print('There are non +ve num or even numbers ')


all  numbers are positive


In [18]:
variable = 42

if isinstance(variable, int):
    print("Variable is an integer")
elif isinstance(variable, str):
    print("Variable is a string")
else:
    print("Variable is of an unknown type")


Variable is an integer


In [ ]:
File Handling and Validation

In [22]:
import os

file_path = input("Enter the path of the file: ")

if os.path.exists(file_path):
    if os.path.isfile(file_path):
        with open(file_path, 'r') as file:
            content = file.read()
            print(f"File content:\n{content}")
    else:
        print("The specified path does not point to a file.")
else:
    print("File not found at the specified path.")


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 48: invalid start byte

In [26]:
l = [5,10,12,14,25,36,18,15,17,23]
list1=[]
for item in l:
    if item%2==0:
        list1.append(item)
print("The list using for loop:",list1)

The list using for loop: [10, 12, 14, 36, 18]


In [28]:
l = [5,10,12,14,25,36,18,15,17,23]
list1=[item for item in l if item%2==0]
print("resultant list using list comprehension:", list1)

resultant list using list comprehension: [10, 12, 14, 36, 18]


In [29]:
# given a list of numbers, find the squares of the numbers using the map function in python
def square(x):
    return x*x
num=[1,2,3,4,5]
num_squared=map(square,num)
for num in num_squared:
    print(num)

1
4
9
16
25


In [35]:
# write a program to filter out the numbers division by 3 from a tuple using lambda function
my_tup=(5,12,10,18,43,9,7,11,6)
new_tup=tuple(filter(lambda x: (x%3==0),my_tup))
print(new_tup)


(12, 18, 9, 6)


In [37]:
# how to create a dataframe in dictionary
import pandas as pd
Emp={'name':['amy','lokesh','shyam','hari'],
     'age':[35,36,37,38],
     'city':['goa','blr','hyd','pune']
}
print(Emp)

{'name': ['amy', 'lokesh', 'shyam', 'hari'], 'age': [35, 36, 37, 38], 'city': ['goa', 'blr', 'hyd', 'pune']}


In [38]:
df=pd.DataFrame(Emp)

In [39]:
df

name  age  city
0     amy   35   goa
1  lokesh   36   blr
2   shyam   37   hyd
3    hari   38  pune

In [ ]:
# whats the difference between loc and iloc in python
loc uses rows and coloumns labels to select and slice data from a DataFrame
iloc uses integer index to select specefic and rows and coloumns
 

In [40]:
df=pd.read_csv(r"C:\Users\User\Desktop\diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [41]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [42]:
df.loc[2:5,['Glucose','Insulin']]

Glucose  Insulin
2      183        0
3       89       94
4      137      168
5      116        0

In [43]:
df.iloc[2:5,1:4]

Glucose  BloodPressure  SkinThickness
2      183             64              0
3       89             66             23
4      137             40             35

In [ ]:
# how is list.append different from the list.extend
list.append() adds the its single element to the end of the list. The length of the list increases by one

list.extend() iterates over its orguments and adds each element to the list. The lenth of the list incresses by the number of number elements in its argument.

In [46]:
list1=['India','USA','Canada']
print(len(list1))
list1.append(['France','Spain'])
print(list1)
print(len(list1))

3
['India', 'USA', 'Canada', ['France', 'Spain']]
4


In [48]:
list1=['India','USA','Canada']
print(len(list1))
list1.extend(['France','Spain'])
print(list1)
print(len(list1))

3
['India', 'USA', 'Canada', 'France', 'Spain']
5


create 4*4 matrix and find the summ of all the diagonal elements in the matrix

In [49]:
import numpy as np

In [52]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [54]:
m=np.arange(1,17).reshape(4,4)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [55]:
print(m.diagonal())

[ 1  6 11 16]


In [56]:
print(m.diagonal().sum())

34


microsoft interview

In [57]:
a=[1,2,3,4,5]
sum=0
for ele in a:
    sum+=ele
print(sum)

15


Given a list of integers and a integer target, return indices of the two numbers such that they add up tp target.

In [58]:
def twosum(nums,target):
    for i in range(len(nums)):
        for j in range(i+1,len(nums)):
            if nums[j]==target-nums[i]:
                return [i,j]

In [59]:
print(twosum([1,5,7,2],12))

[1, 2]


Python pandas interview Q&A Mindmajix

define pandas?

In [63]:
pandas refer to a data analysis  and manipulation software library build specifically by python. pandas opensourse
and cross platform library.


SyntaxError: invalid syntax (324314765.py, line 1)

Mention different types of data structures in pandas?

series and DataFrames are the two types of data strutures that the pandas library supports Numpy serves as the foundation 
for both data strutures.

series is 1 dimentional data structure

DataFrame is 2 dimetional data structure

what is python pandas used for?

pandas is data manipulation and analysis software library for the python programming laguage. It includes data structure
and methods for manipulating numerical tables and time series in particular.

List out key feature of pandas library?

memory efficient

Time series

reshaping

data alignment

merge and join

Explain how to create and copy a series in python

In [71]:
list(range(5))

[0, 1, 2, 3, 4]

In [75]:
digi = [0, 1, 5, 7]
for data in digi:
    if data==4:
        break
    print(data)
else:
    print("Loop Success")

0
1
5
7
Loop Success


In [77]:
for i in range(1,20,2):
    if i==15:
        break
    print(i)
else:
    print('Iterated over everything :)')

1
3
5
7
9
11
13


In [80]:
for i in range(1,10):
    if i == 3:
        continue
    print(i)

1
2
4
5
6
7
8
9


In [81]:
x=1
while x<=5:
    print(x)
    x=x+1
print("loop Finished")

1
2
3
4
5
loop Finished


In [82]:
i = 2
while(i < 100):
   j = 2
   while(j <= (i/j)):
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print (i," is prime")
   i = i + 1
print ("Good bye!")

2  is prime
3  is prime
5  is prime
7  is prime
11  is prime
13  is prime
17  is prime
19  is prime
23  is prime
29  is prime
31  is prime
37  is prime
41  is prime
43  is prime
47  is prime
53  is prime
59  is prime
61  is prime
67  is prime
71  is prime
73  is prime
79  is prime
83  is prime
89  is prime
97  is prime
Good bye!


In [83]:
 for a in range(1,3):
       for b in range(1,3):
           print(a,b)

1 1
1 2
2 1
2 2


pattern program

1. Input: how many rows contains

2. for loop: two for loops rows and columns

3. range: 

4.print(): print("hello"), print('hi')

In [88]:
num=int(input("Enter the number of rows:"))
for i in range(1,num+1):
    for j in range(1,i+1):
        print("*", end="")
    print()

*
**
***
****
*****


In [3]:
str1="PYTHON"
print(str1.isdigit())
str2="12345"
print(str2.isdigit())
str3="Hello123"
print(str3.isdigit())



False
True
False


AttributeError: 'int' object has no attribute 'isdigit'

In [4]:
PyStr="PYTHON"
print(PyStr.islower())
PyStr="python"
print(PyStr.islower())
PyStr="pYthOn"
print(PyStr.islower())


False
True
False


In [5]:
PyStr="PYTHON"
print(len(PyStr))
PyStr="DataScience is ROCKING"
print(len(PyStr))


6
22


In [6]:
PyList=['1','2','3','4']  
Sep="-"
print(Sep.join(PyList))


1-2-3-4


In [7]:
PyList=["H","E","L","L","O"]
Sep="__"
print(Sep.join(PyList))

H__E__L__L__O


In [8]:
PyStr="abcd"
print(max(PyStr))
PyStr="abcddcba"
print(max(PyStr))
PyStr="Maximum"
print(max(PyStr))

d
d
x


In [9]:
str = "Hello How are You"
print(str.replace("You", "U"))
print(str.replace("are", "was", 3))


Hello How are U
Hello How was You


In [10]:
PyStr="2009"; 
print(PyStr.isalnum())
PyStr="this"; 
print(PyStr.isalnum())
PyStr="this2009"; 
print(PyStr.isalnum())
PyStr="this string example....wow"
print(PyStr.isalnum())


True
True
True
False


In [11]:
alist = ['a', 'b', 'c']
alist.append(['d', 'e','f'])
print(alist)


['a', 'b', 'c', ['d', 'e', 'f']]


In [12]:
py_list=["Big Data", "Hadoop", "Spark", "IoT"]  
print(py_list[0])  
py_list[0]="DataScinece" 
print(py_list)  
print(py_list[0]) 

Big Data
['DataScinece', 'Hadoop', 'Spark', 'IoT']
DataScinece


In [14]:
alist1 = ['a', 'b', 'c']
alist1.extend(['d', 'e','f','d'])
print(alist1)

['a', 'b', 'c', 'd', 'e', 'f', 'd']


In [15]:
MyData = ['Big', 'Data', 'Hadoop', 'Spark']
MyData.insert(2, 'TERADATA')
print('Updated List: ', MyData)

Updated List:  ['Big', 'Data', 'TERADATA', 'Hadoop', 'Spark']


In [16]:
py_list=["Big Data", "Hadoop", "Spark", "IoT"]  
print(py_list)  
py_list.remove("IoT")  
print(py_list) 

['Big Data', 'Hadoop', 'Spark', 'IoT']
['Big Data', 'Hadoop', 'Spark']


In [17]:
Fruit_List = ["Apple", "Banana", "Cherry", "Jackfruit", "Grape"]
del Fruit_List[0]
print(Fruit_List)


['Banana', 'Cherry', 'Jackfruit', 'Grape']


In [18]:
py_list=["Big Data", "Hadoop", "Spark", "IoT"]  
print(py_list)  
py_list.clear()  
print(py_list)

['Big Data', 'Hadoop', 'Spark', 'IoT']
[]


In [19]:
PyList=[1,2,3,3,2,1,5,4]
print(PyList)
print(PyList.index(1))
print(PyList.index(3))
print(PyList.index(4))
print(PyList.index(3,3))
print(PyList.index(1,3))
print(PyList.index(2,4))
print(PyList.index(4,4,10))

[1, 2, 3, 3, 2, 1, 5, 4]
0
2
7
3
5
4
7


In [20]:
PyList=[1,2,3,1,4,5,2,5,6,1,4]
print(PyList)
print(PyList.index(2))
print(PyList.index(2,2))
print(PyList.index(1,2,7))
print(PyList.index(4,3,9))


[1, 2, 3, 1, 4, 5, 2, 5, 6, 1, 4]
1
6
3
4


In [21]:
PyList=["Data","ML","DL","Data","ML"]
print(PyList)#['Data','ML','DL','Data','ML']
print(PyList.index("ML"))
print(PyList.index("Data"))
print(PyList.index("Data",1))
print(PyList.index("ML",2,6))


['Data', 'ML', 'DL', 'Data', 'ML']
1
0
3
4


In [22]:
listy = list("HELLO WORLD")  
print(listy)  
index = listy.index("L")
print(index)  
index = listy.index("L", 4)   
print(index)  
index = listy.index("O", 3, 5) 
print(index) 


['H', 'E', 'L', 'L', 'O', ' ', 'W', 'O', 'R', 'L', 'D']
2
9
4


In [23]:
PyList=[[1,2],[2,4],[4,5],[3,1]]
print(PyList)
PyList.sort()
print(PyList)

[[1, 2], [2, 4], [4, 5], [3, 1]]
[[1, 2], [2, 4], [3, 1], [4, 5]]


In [1]:
s = [1, 3, 4, 5]
print(all(s))

s = [0, False]
print(all(s))

True
False


In [2]:
BigData=['Big Data', 'Hadoop', 'Spark','Data Science']
eData = enumerate(BigData)
print(type(eData))
print(list(eData))

<class 'enumerate'>
[(0, 'Big Data'), (1, 'Hadoop'), (2, 'Spark'), (3, 'Data Science')]


In [3]:
bd = ['Big Data', 'Hadoop', 'Spark','Data Science']
for item in enumerate(bd):
  print(item)


(0, 'Big Data')
(1, 'Hadoop')
(2, 'Spark')
(3, 'Data Science')


In [4]:
bd = ['Big Data', 'Hadoop', 'Spark','Data Science']
for count, item in enumerate(bd):
  print(count, item)

0 Big Data
1 Hadoop
2 Spark
3 Data Science


In [5]:
bd = ['Big Data', 'Hadoop', 'Spark','Data Science']
for count, item in enumerate(bd, 100):
  print(count, item)

100 Big Data
101 Hadoop
102 Spark
103 Data Science


In [6]:
names = ['Bob', 'Alice', 'Guido']
print(list(enumerate(names)))

[(0, 'Bob'), (1, 'Alice'), (2, 'Guido')]


In [7]:
names = ['Bob', 'Alice', 'Guido']
for index, value in enumerate(names):
    print(f'{index}: {value}')

0: Bob
1: Alice
2: Guido


In [8]:
a = ["b", "g", "a", "d", "f", "c", "h", "e"]#List
x = sorted(a)
print(x)
a = ("b", "g", "a", "d", "f", "c", "h", "e")#Tuple
x = sorted(a)
print(x)
a = {"b":"g", "a":"d", "f":"c", "h":"e"}#Dictionary
x = sorted(a)
print(x)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
['a', 'b', 'f', 'h']


In [9]:
a = ["bb", "ggg", "aaaa", "dddd", "ff"]
x = sorted(a,key=len)
print(x)
a = ("bb", "ggg", "aaaa", "dddd", "ff")
x = sorted(a,key=len)
print(x)
a = {"bb":"ggg", "aaaa":"d", "ff":"c"}
x = sorted(a,key=len)
print(x)

['bb', 'ff', 'ggg', 'aaaa', 'dddd']
['bb', 'ff', 'ggg', 'aaaa', 'dddd']
['bb', 'ff', 'aaaa']


In [10]:
a = {"bb":"ggg", "aaaa":"d", "ff":"c"}
x = sorted(a,key=len)
print(x)
print(sorted(a.values()))
print(sorted(a.keys()))
print(sorted(a.items()))

['bb', 'ff', 'aaaa']
['c', 'd', 'ggg']
['aaaa', 'bb', 'ff']
[('aaaa', 'd'), ('bb', 'ggg'), ('ff', 'c')]


In [11]:
A=[1]*2
print(A)
B=[[1]*2]*5
print(B)
C=[[2,0]*1]*4
print(C)


[1, 1]
[[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
[[2, 0], [2, 0], [2, 0], [2, 0]]


In [12]:
A=[[1]*2]*5
print(A)
B=[[2,0]*1]*4
print(B)

[[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
[[2, 0], [2, 0], [2, 0], [2, 0]]


In [13]:
A=[2]*3
print(A)
B=[[2]*3]*2
print(B)
C=[[1,0]*1]*5
print(C)

[2, 2, 2]
[[2, 2, 2], [2, 2, 2]]
[[1, 0], [1, 0], [1, 0], [1, 0], [1, 0]]


In [14]:
A=[1,2,3,4,5]
print(A[0]*2)
print(A*2)
print(A[3]*3)
print(A[4]*1)
print(A*3)

2
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
12
5
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [15]:
PyList=[1,[2,[3,[4,[5]]]]]
print(PyList[0])
print(PyList[1][0])
print(PyList[1][1][0])

1
2
3


In [16]:
result=[x**2 for x in [3,4,5]]
print(result)

[9, 16, 25]


In [17]:
print([x*1 for x in [1,2,3,4]])
print([x*2 for x in [1,2,3,4]])
print([x**2 for x in [1,2,3,4]])
print([x**2 for x in [1,2,3,4] if x%2==0])
print([x**2 for x in [1,2,3,4] if x%2!=0])

[1, 2, 3, 4]
[2, 4, 6, 8]
[1, 4, 9, 16]
[4, 16]
[1, 9]


In [18]:
num=[1,2,3,4]
result=[x*10 for x in num]
print(result)


[10, 20, 30, 40]


In [19]:
print([x for x  in "Hello12345" if x.isdigit()])
print([x for x  in "Hello12345" if x.isalpha()])

['1', '2', '3', '4', '5']
['H', 'e', 'l', 'l', 'o']


In [20]:
words=['Hello',"Hai",'python']
result=[x.upper() for x in words]
print(result)

['HELLO', 'HAI', 'PYTHON']


In [21]:
Sample_List = ["Sample", "List"]
Result = [item[0] for item in Sample_List]
print(Result)

['S', 'L']


In [22]:
a=[1,2,3,4,5,6]
b=[2,3]
result=[x+y for x in a for y in b]
print(result )

[3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9]


In [23]:
myList=[1,2,3,4,5,6]
print(myList)
yourList=myList
print(yourList)
myList[0]="NareshIT"
print(myList)
print(yourList)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
['NareshIT', 2, 3, 4, 5, 6]
['NareshIT', 2, 3, 4, 5, 6]


In [24]:
import copy
myList=[1,2,3,4,5,6]
print(myList)
yourList=myList
print(yourList)
myList=copy.copy(yourList)
myList[4]="PYTHON"
print(myList)
print(yourList)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 'PYTHON', 6]
[1, 2, 3, 4, 5, 6]


In [25]:
import copy
old_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
new_list = copy.copy(old_list)
old_list.append([4, 4, 4])
print("Old list:", old_list)
print("New list:", new_list)

Old list: [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]
New list: [[1, 1, 1], [2, 2, 2], [3, 3, 3]]


In [26]:
import copy
yourList=[1,2,3,4,['a','b','c']]
myList=copy.deepcopy(yourList)
myList[4][1]="Hello"
print(myList)
print(yourList)

[1, 2, 3, 4, ['a', 'Hello', 'c']]
[1, 2, 3, 4, ['a', 'b', 'c']]


In [27]:
PyList1=["Hadoop","Spark","PYTHON","DataScience"]
PyList2=["Bigdata","Teradata","Pandas","SKLearn"]
z1=zip(PyList1,PyList2)
print(list(z1))

[('Hadoop', 'Bigdata'), ('Spark', 'Teradata'), ('PYTHON', 'Pandas'), ('DataScience', 'SKLearn')]


In [28]:
Pylist1=[1,2]
Pylist2=[2,3]
ziplist=zip(Pylist1,Pylist2)
ziptuple=zip(Pylist1,Pylist2)
zipset=zip(Pylist1,Pylist2)
zipdict=zip(Pylist1,Pylist2)
print(list(ziplist))
print(tuple(ziptuple))
print(set(zipset))
print(dict(zipdict))


[(1, 2), (2, 3)]
((1, 2), (2, 3))
{(2, 3), (1, 2)}
{1: 2, 2: 3}


In [29]:
PyList1=[10,20,30,40]
PyList2=[50,60,70,80]
for a,b in zip(PyList1,PyList2):
    print('{} + {}={}'.format(a,b,a+b))

10 + 50=60
20 + 60=80
30 + 70=100
40 + 80=120


In [30]:
PyList1=["Hadoop","Spark","PYTHON","DataScience"]
PyList2=["Bigdata","Teradata","Pandas","SKLearn"]
z1=zip(PyList1,PyList2)
z2=zip(*z1)
print(*z2)

('Hadoop', 'Spark', 'PYTHON', 'DataScience') ('Bigdata', 'Teradata', 'Pandas', 'SKLearn')


In [31]:
PyFruits=["Apple", "Banana", "Mango", "Grapes", "Orange"]
print(PyFruits[1:4])
print(PyFruits[ :3])
print(PyFruits[-4:])
print(PyFruits[-3:-1])

['Banana', 'Mango', 'Grapes']
['Apple', 'Banana', 'Mango']
['Banana', 'Mango', 'Grapes', 'Orange']
['Mango', 'Grapes']


In [32]:
MyTuple=('a',[1,2])
print(type(MyTuple))
print(MyTuple[0])
print(MyTuple[1])
print(MyTuple[1][1])
MyTuple[1][1]='4'
print(MyTuple)

<class 'tuple'>
a
[1, 2]
2
('a', [1, '4'])


In [33]:
PyTuple = (2, 4, 3, 5, 4, 6, 7, 8, 6, 1)   
print(PyTuple[3:5])
print(PyTuple[:6])
print(PyTuple[5:])
print(PyTuple[:])
print(PyTuple[-8:-4])

(5, 4)
(2, 4, 3, 5, 4, 6)
(6, 7, 8, 6, 1)
(2, 4, 3, 5, 4, 6, 7, 8, 6, 1)
(3, 5, 4, 6)


In [34]:
A={10,20,30}; B=[40,50,60,10]
A.update(B,range(5))
print(A)


{0, 1, 2, 3, 4, 40, 10, 50, 20, 60, 30}


In [39]:
def fun(a,b,c):
  print(a,b,c)
fun(c=3,b=2,a=1)


1 2 3


In [40]:
def nsquare(x, y = 2):  
    return (x*x+y*y)  
print("The square of the sum of 2 and 3 is : ", nsquare(2))  
print("The square of the sum of 2 and 3 is : ", nsquare(2,4))

The square of the sum of 2 and 3 is :  8
The square of the sum of 2 and 3 is :  20


In [41]:
def printinfo( name, exp = '15+' ):
    print("Name: ", name)
    print("Experience: ", exp)
    return;
printinfo( exp=14, name="KSRaju" )
printinfo( name="NareshIT" )

Name:  KSRaju
Experience:  14
Name:  NareshIT
Experience:  15+


In [42]:
def Scores(BigData,Hadoop=85,Spark=80):  
    print(BigData,Hadoop,Spark)  
Scores(71,77)  
Scores(65,Spark=74)  
Scores(BigData=70,Hadoop=90,Spark=75) 


71 77 80
65 85 74
70 90 75


In [43]:
def fun(*arr):
  for val in arr:
    print(val)
fun(1,2,3,4)

1
2
3
4


In [44]:
def fun1(*var):
   for x in var:
      print(x)
fun( 70, 60, 50 )

70
60
50


In [45]:
import modulethree as mt
Sum=mt.add(10,20)
print("Sum of the numbers is: " ,Sum)
dif=mt.sub(20,10)
print("Difference of the numbers is: " ,dif)
prd=mt.prod(10,10)
print("Difference of the numbers is: " ,prd)

ModuleNotFoundError: No module named 'modulethree'

In [46]:
a="BigData"
b="Hadoop"
c="Spark"
d="Data Science"
print(a,b,c,d)
print(a,d)

BigData Hadoop Spark Data Science
BigData Data Science


In [52]:
def Add1(a,b):
    return(a+b)
def Sub1(a,b):
    return(a-b)
def Pro1(a,b):
    return(a*b)
def Div1(a,b):
    return(a/b)
def FDiv1(a,b):
    return(a//b)

In [53]:
print(abs(-45))
print(abs(100.12))

45
100.12


In [54]:
import math 
print(math.ceil(-45.17))
print (math.ceil(100.12))
print (math.ceil(100.72))


-45
101
101


AttributeError: 'list' object has no attribute 'enumurate'

In [56]:
try:
  x=int(input("Enter a value: "))
  print("Try Block:Enter Number is: ",x)
except ValueError:
  print("ExceptBlock:Invalid Input Enter Only Numbers");


Try Block:Enter Number is:  5


In [57]:
try:
  x=int(input("Enter Required Number: "))
  y=int(input("Enter Required Number: "))
  print("The Result is: ",x/y)
except Exception as arg:
    print("You can't divide by zero.")
    print('Error: ', arg)

You can't divide by zero.
Error:  division by zero


In [58]:
try:
  x=int(input("Enter Required Number: "))
  y=int(input("Enter Required Number: "))
  print("The Result is: ",x/y)
except Exception as arg:
    print("You can't divide by zero.")
    print('Error: ', arg)

The Result is:  4.0


In [60]:
try:
    p=int(input("Enter Any Number: "))
    q=int(input("Enter Any Number: "))
    r=p/q
    print("The Value is: ",int(r))
    print("TryBlockIsExecuted:")
except ValueError:
    print("ExceptBlock")
    print("Sorry User Numbers Only Valid")
except Exception as arg:
    print("You can't divide by zero.")
    print('Error: ', arg)

The Value is:  0
TryBlockIsExecuted:


In [61]:
try:
    fi=open("Hai1.txt",'r')
    print(fi.read(6))
except IOError:
    print("File Not Existed Please Create")
else:
    print("ContentReadSuccessfully")
    fi.close()


File Not Existed Please Create


In [62]:
def Hello():
    print("Wish Programmers")
print(type(Hello))

<class 'function'>


In [65]:
class Account:
    #"""This is docstring, explains brief about the class"""
	pass
sb_account=Account()
current_account=Account()

TabError: inconsistent use of tabs and spaces in indentation (1455693342.py, line 3)

In [66]:
class Car():
    pass
print(Car)
print(type(Car))
print(Car.__name__)
print(Car.__doc__)

<class '__main__.Car'>
<class 'type'>
Car
None


In [68]:
class BankAccount:
    def __init__(self, account_holder, balance=0.0):
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited ${amount}. New balance: ${self.balance}")
        else:
            print("Invalid deposit amount.")

    def withdraw(self, amount):
        if 0 < amount <= self.balance:
            self.balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.balance}")
        else:
            print("Invalid withdrawal amount or insufficient funds.")

    def get_balance(self):
        return self.balance

    def display_account_info(self):
        print(f"Account Holder: {self.account_holder}")
        print(f"Balance: ${self.balance}")


# Example usage:

# Create an account
john_account = BankAccount(account_holder="John Doe", balance=1000.0)

# Deposit money
john_account.deposit(500.0)

# Withdraw money
john_account.withdraw(200.0)

# Display account information
john_account.display_account_info()


Deposited $500.0. New balance: $1500.0
Withdrew $200.0. New balance: $1300.0
Account Holder: John Doe
Balance: $1300.0


In [69]:
class Product:
    def __init__(self, product_id, name, price):
        self.product_id = product_id
        self.name = name
        self.price = price

    def display_product_info(self):
        print(f"Product ID: {self.product_id}")
        print(f"Name: {self.name}")
        print(f"Price: ${self.price}")


class Customer:
    def __init__(self, customer_id, name, email):
        self.customer_id = customer_id
        self.name = name
        self.email = email

    def display_customer_info(self):
        print(f"Customer ID: {self.customer_id}")
        print(f"Name: {self.name}")
        print(f"Email: {self.email}")


class Order:
    def __init__(self, order_id, customer, products=None):
        self.order_id = order_id
        self.customer = customer
        self.products = products or []

    def add_product(self, product, quantity=1):
        for _ in range(quantity):
            self.products.append(product)

    def calculate_total(self):
        total = sum(product.price for product in self.products)
        return total

    def display_order_summary(self):
        print(f"Order ID: {self.order_id}")
        self.customer.display_customer_info()
        print("\nProducts in the order:")
        for product in self.products:
            product.display_product_info()
        print(f"\nTotal: ${self.calculate_total()}")


# Example usage:

# Create products
product1 = Product(product_id=1, name="Laptop", price=1200.0)
product2 = Product(product_id=2, name="Mouse", price=20.0)

# Create a customer
customer = Customer(customer_id=1, name="John Doe", email="john@example.com")

# Create an order
order = Order(order_id=1, customer=customer)

# Add products to the order
order.add_product(product1, quantity=2)
order.add_product(product2)

# Display order summary
order.display_order_summary()


Order ID: 1
Customer ID: 1
Name: John Doe
Email: john@example.com

Products in the order:
Product ID: 1
Name: Laptop
Price: $1200.0
Product ID: 1
Name: Laptop
Price: $1200.0
Product ID: 2
Name: Mouse
Price: $20.0

Total: $2420.0


In [1]:
class Author:
    def __init__(self, author_id, name, email):
        self.author_id = author_id
        self.name = name
        self.email = email

    def display_author_info(self):
        print(f"Author ID: {self.author_id}")
        print(f"Name: {self.name}")
        print(f"Email: {self.email}")


class Post:
    def __init__(self, post_id, title, content, author, date_published):
        self.post_id = post_id
        self.title = title
        self.content = content
        self.author = author
        self.date_published = date_published

    def display_post_info(self):
        print(f"Post ID: {self.post_id}")
        print(f"Title: {self.title}")
        print(f"Content: {self.content}")
        print(f"Author: {self.author.name}")
        print(f"Date Published: {self.date_published}")


class Blog:
    def __init__(self, blog_id, name, posts=None):
        self.blog_id = blog_id
        self.name = name
        self.posts = posts or []

    def add_post(self, post):
        self.posts.append(post)

    def display_blog_info(self):
        print(f"Blog ID: {self.blog_id}")
        print(f"Name: {self.name}")
        print("\nPosts in the blog:")
        for post in self.posts:
            post.display_post_info()


# Example usage:

# Create authors
author1 = Author(author_id=1, name="Alice Author", email="alice@example.com")
author2 = Author(author_id=2, name="Bob Blogger", email="bob@example.com")

# Create posts
post1 = Post(post_id=1, title="Introduction to Python", content="Python is a powerful programming language.", author=author1, date_published="2023-01-01")
post2 = Post(post_id=2, title="Web Development with Django", content="Django is a web framework for Python.", author=author2, date_published="2023-02-01")

# Create a blog
blog = Blog(blog_id=1, name="Tech Blog")

# Add posts to the blog
blog.add_post(post1)
blog.add_post(post2)

# Display blog information
blog.display_blog_info()


Blog ID: 1
Name: Tech Blog

Posts in the blog:
Post ID: 1
Title: Introduction to Python
Content: Python is a powerful programming language.
Author: Alice Author
Date Published: 2023-01-01
Post ID: 2
Title: Web Development with Django
Content: Django is a web framework for Python.
Author: Bob Blogger
Date Published: 2023-02-01


PYTHON OOPS CONCEPTS

In [1]:
WORKING WITH PYTHON OOPs
PYTHON Object Oriented Programming System:(OOPs)

Python is truely object oriented programming language. In Python everything is an Object like:classes, objects, 
functions, methods, modules etc..These can passed as arguments to functions or assign to variables.

OOPS Principles

Oops are the rules (or) guidelines which are supposed to be satisfied by any programming language in order to 
call that programming language as oopl. Different oops principles are:

1. Class		2. Object		3.Inheritance	4.Polymorphism 	5.Encapsulation 6.Abstraction


SyntaxError: invalid decimal literal (3287714543.py, line 12)

1. Class

Define Class?
Class can be described as :
1 Pre-defined keyword.
2 Class is Template or Blue print for Objects
3 Collections of variables and methods
4 Collection of objects that has common properties 


Example:
Class Name ==> Phone
Rotary Phone	Cellular Phone	
Mobile Phone	Touch Phone


NOTE:
Class Name should starts with Capital letter, It is convention in PYTHON

Define Object?
Collection of data and its functionality.
OR
It is an entity that has states & behaviors is known as Object.
OR
An Object is an instance of class, which contains attributes & methods

In [2]:
Define Reference Variable?
The variable which can be used to refer object is called reference variable. By using reference variable, we can access properties and methods of object.

NOTE: 
State means Properties/Attributes, Behaviour means methods/functionalities.

Example:
Object1: Human
Identity: Midhun
Properties: Color, Height, Weight
Functionalities: walk () , see() , run() ....


SyntaxError: invalid syntax (2098518563.py, line 2)

In [4]:
#Example:
class MyBank_SBI():
           pass
class MyBank_AB:
          pass
class MyBank_HDFC(object):
          pass
#SS is an Object or Instance
SS=MyBank_SBI()
print(SS)
#AA is an Object or Instance
AA=MyBank_AB()
print(AA)
#HH is an Object or Instance
HH=MyBank_HDFC()
print(HH)


NOTE:
Instance indicates relationship between an Object to its Class (Instanace means reference)


In [5]:
class Banking():
    #Class Body or Logic
    print("Welcome to Banking")
#Creating Instance or Object
#Driver Code
BB=Banking()
print(BB)#display the address of Object or Instance

Welcome to Banking


In [6]:
class Banking():
#It is a Method of Member
#Class inside all are members
    def MyCustomer():
        print("Welcome to Banking")
        return()
#Driver Code
BB=Banking()
BB.MyCustomer()
#TypeError: MyCustomer() takes 0 positional arguments but 1 was given

TypeError: Banking.MyCustomer() takes 0 positional arguments but 1 was given

Self variable:
self is the default variable which is always pointing to current object (like this keyword in JAVA) By using self we can access instance variables and instance methods of object.

In [7]:
class Banking():
    def MyCustomer(self):
        print("Welcome to Banking")
        return()
#Driver Code
BB=Banking()
BB.MyCustomer()


Welcome to Banking


()

In [8]:
class Human():
    "This class demonstrates the creation of Objects"
    #Instance Attributes
    num=100
    #Instance Method
    def EampleMethod(self):
        print("I am a method inside the class")

In [9]:
#Creating Object or Instance of Human Class
HH=Human()
print(HH.num)
#Calling Method
HH.EampleMethod()
print(Human.__doc__)
print(help(Human))

100
I am a method inside the class
This class demonstrates the creation of Objects
Help on class Human in module __main__:

class Human(builtins.object)
 |  This class demonstrates the creation of Objects
 |  
 |  Methods defined here:
 |  
 |  EampleMethod(self)
 |      #Instance Method
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  num = 100

None


OOPS IN PYTHON:

1. Classes and objects

2. Inheritance

3. Polymorphism

4. Abstraction

5. Encapsulation



Python Class

1. Is a blueprint, architecture, design, planning 

2. Object is the base class in python

3. Class keyword is used to create a class

4. python constructure is defined with __init__() method

5. python does't support multiple constructors in a class i.e No constructor overloading 


In [1]:
 
class Kiran():
    print("This is class")


This is class


In [5]:
 
class Kiran():
    d=12
    print("This is class")
    def display(self):
        a=10
        b=12
        print(a,b)
    #display()
        # in class we have to create a object to calling a class
obj=Kiran()
obj.display()
print(obj.d)

This is class
10 12
12


In [16]:
class Mobile():
    def __init__(self,brand,battery,ram,camera,price):
        self.brand=brand
        self.battery=battery
        self.ram=ram
        self.camera=camera
        self.price=price
    def display(self):
        print("brand:",self.brand)
        print("battery:",self.battery)
        print("ram:",self.ram)
        print("camera",self.camera)
        print("price:",self.price)
        print("----------------------")
for i in range(5):
    
    obj=Mobile("apple","4000mah","8gp","48mp","9000")

    obj.display()
    obj2=Mobile("oneplus","7000mah","16gp","80mp","12000")
    obj2.display()

    

brand: apple
battery: 4000mah
ram: 8gp
camera 48mp
price: 9000
----------------------
brand: oneplus
battery: 7000mah
ram: 16gp
camera 80mp
price: 12000
----------------------
brand: apple
battery: 4000mah
ram: 8gp
camera 48mp
price: 9000
----------------------
brand: oneplus
battery: 7000mah
ram: 16gp
camera 80mp
price: 12000
----------------------
brand: apple
battery: 4000mah
ram: 8gp
camera 48mp
price: 9000
----------------------
brand: oneplus
battery: 7000mah
ram: 16gp
camera 80mp
price: 12000
----------------------
brand: apple
battery: 4000mah
ram: 8gp
camera 48mp
price: 9000
----------------------
brand: oneplus
battery: 7000mah
ram: 16gp
camera 80mp
price: 12000
----------------------
brand: apple
battery: 4000mah
ram: 8gp
camera 48mp
price: 9000
----------------------
brand: oneplus
battery: 7000mah
ram: 16gp
camera 80mp
price: 12000
----------------------


In [5]:
class Mobile():
    def __init__(self):
        print("This is Init")
    def display(self):
        print('This is method:')

obj=Mobile()
obj.display()

This is Init
This is method:


2. Inheritance

ClassA--------ClassB ------ Single Inheritance
ClassA--------ClassB------- ClassC-- Multilevel Inheritance

                                 ClassA

                            ClassB         ClassC     Hierarchical Inheritance


                            ClassA

                    ClassB         ClassC          Multiple Inheritance

In [7]:
# 1.single Inheritance
class Parent:
    def fun1(self):
        print("This is parent class")
class Child(Parent):
    def fun2(self):
        print("This is Parent class")

        # we have to create a objects in child class only because what ever there properties we are inherting from parent

obj=Child()
obj.fun2()
obj.fun1()
    

This is Parent class
This is parent class


In [14]:
# 2.Multilevel Inheritance
class Parent:
    def fun1(self):
        print("This is parent class")
class Child(Parent):
    def fun2(self):
        print("This is Child class")

class GrandChild(Child):
    def fun3(self):
        print("This is GrandChild class")


        # we have to create a objects in child class only because what ever there properties we are inherting from parent

obj=GrandChild()
obj.fun2()
obj.fun1()
obj.fun3()
    

This is Child class
This is parent class
This is GrandChild class


In [19]:
#3. Hirarchical Inheritance --- One parent class two child classes its will come 

class Parent:
    def fun1(self):
        print("This is parent class")
class Child1(Parent):
    def fun2(self):
        print("This is Child1 class")

class Child2(Parent):
    def fun3(self):
        print("This is Child2 class")


        # we have to create a objects in child class only because what ever there properties we are inherting from parent

obj=Child2()
#obj.fun2()
obj.fun1()
obj.fun3() 
obj=Child1()# hire creating object separately 
obj.fun2()

This is parent class
This is Child2 class
This is Child1 class


In [23]:
#3. Multiple Inheritance --- Two parent class one child classes its will come 

class Father():
    def fun1(self):
        print("This is Fatehr class")
class Mother():
    def fun2(self):
        print("This is Mother class")

class Child(Father,Mother):
    def fun3(self):
        print("This is Father,Mother class")


        # we have to create a objects in child class only because what ever there properties we are inherting from parent

obj=Child()
obj.fun2()
obj.fun1()
obj.fun3() 


This is Mother class
This is Fatehr class
This is Father,Mother class


In [25]:
# super class------ parent class to child access the objects using super 

class A():
    def __init__(self):
        print("This is class A")
    def fun1(self):
        print("This is Fatehr class")
class B(A):
    def __init__(self):
        print("This is class B")
        super().__init__()
    def fun2(self):
        print("This is Mother class")

obj=B()



This is class B
This is class A


# 3. Polymorphism   multiple forms more than one form

1.Compile time

Method over-loading --- same class same function names but different parametars


2.Run time


Method over-riding ---- diffrent classes ,different parametars but same function name

In [30]:
#method oveloading- 
#same class same function names but different parametars

class A():
    def sum(self,a,b):
        return a+b 
    def sum(self,a,b,c=1):
        return a+b+c 
    # whom you are calling exatly not identified
obj=A()
print(obj.sum(5,12,3))

20


In [32]:
#method overiding
#diffrent classes ,different parametars but same function name
class A():
    def display(self):
        print("This is class A")
class B(A):
    def display(self):
        print("This is class B")
        super().display()
obj=B()
obj.display()

This is class B
This is class A


In [36]:
# Abstraction----Hiding of data---- Example: ATM Mechine we cannoot see the inside functiolity 

from abc import ABC, abstractmethod

# Abstract class representing a Shape
class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def perimeter(self):
        pass

# Concrete class Circle that extends Shape
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius ** 2

    def perimeter(self):
        return 2 * 3.14 * self.radius

# Concrete class Square that extends Shape
class Square(Shape):
    def __init__(self, side):
        self.side = side

    def area(self):
        return self.side ** 2

    def perimeter(self):
        return 4 * self.side

# Function to calculate and print area and perimeter of a shape
def print_shape_info(shape):
    print(f"Area: {shape.area()}")
    print(f"Perimeter: {shape.perimeter()}\n")

# Example usage
circle = Circle(radius=5)
square = Square(side=4)

# Using the abstraction to calculate and print shape information
print("Circle Information:")
print_shape_info(circle)

print("Square Information:")
print_shape_info(square)


Circle Information:
Area: 78.5
Perimeter: 31.400000000000002

Square Information:
Area: 16
Perimeter: 16



In [35]:
# Encapsulation ---- binding of data members and member functions 
# wrapping of variables and methods into a single unit 
# access specifiers ------ public, privete, protected 
class BankAccount:
    def __init__(self, account_holder, balance=0):
        self._account_holder = account_holder  # Private attribute
        self._balance = balance  # Private attribute

    # Getter methods
    def get_account_holder(self):
        return self._account_holder

    def get_balance(self):
        return self._balance

    # Setter method
    def deposit(self, amount):
        if amount > 0:
            self._balance += amount
            print(f"Deposited ${amount}. New balance: ${self._balance}")
        else:
            print("Invalid deposit amount")

    def withdraw(self, amount):
        if 0 < amount <= self._balance:
            self._balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self._balance}")
        else:
            print("Invalid withdrawal amount")

# Example usage
account1 = BankAccount("John Doe", 1000)

# Accessing attributes using getters
print(f"Account Holder: {account1.get_account_holder()}")
print(f"Balance: ${account1.get_balance()}")

# Performing operations using methods
account1.deposit(500)
account1.withdraw(200)

# Trying to access private attributes directly (will generate an error)
# print(account1._balance)


Account Holder: John Doe
Balance: $1000
Deposited $500. New balance: $1500
Withdrew $200. New balance: $1300


In [26]:
class Animal:
    def make_sound(self):
        print("Generic animal sound")

class Dog(Animal):
    def make_sound(self):
        print("Bark")

class Cat(Animal):
    def make_sound(self):
        print("Meow")

# Create instances
dog = Dog()
cat = Cat()

# Call overridden method
dog.make_sound()  # Output: Bark
cat.make_sound()  # Output: Meow


Bark
Meow


In [33]:
class Calculator:
    def add(self, a, b=None, c=None):
        if b is not None and c is not None:
            return a + b + c
        elif b is not None:
            return a + b
        else:
            return a

# Create an instance
calc = Calculator()

# Call overloaded method
result1 = calc.add(1)
result2 = calc.add(1, 2)
result3 = calc.add(1, 2, 3)

print(result1)  # Output: 1
print(result2)  # Output: 3
print(result3)  # Output: 6


1
3
6


In [34]:
class Calculator:
    def add(self, a, b=None, c=None):
        if b is not None and c is not None:
            return a + b + c
        elif b is not None:
            return a + b
        else:
            return a

# Create an instance
calc = Calculator()

# Call overloaded method
result1 = calc.add(1)
result2 = calc.add(1, 2)
result3 = calc.add(1, 2, 3)

print(result1)  # Output: 1
print(result2)  # Output: 3
print(result3)  # Output: 6


1
3
6
